on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    timeout-minutes: 600
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-43
      options: --privileged
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Prepare Node
        uses: actions/setup-node@v3
      - name: echo
        run: echo $PATH
      - name: Prepare Runtime
        run: |
          flatpak --system install -y --noninteractive flathub org.freedesktop.Sdk.Extension.node18/${{ matrix.arch }}/22.08
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v5
        with:
          bundle: sticky.flatpak
          manifest-path: com.vixalien.sticky.json
          cache-key: flatpak-builder-${{ github.sha }}
          arch: ${{ matrix.arch }}
